# Generated by Django 2.1.7 on 2019-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190621_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='Категория')),
                ('price', models.PositiveSmallIntegerField(max_length=16, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Расценка',
                'verbose_name_plural': 'Расценки',
            },
        ),
    ]
