# Generated by Django 2.1.7 on 2019-06-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
    ]
