# Generated by Django 2.1.7 on 2019-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190623_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image_name', verbose_name='Фото')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('surname', models.CharField(max_length=16, verbose_name='Фамилия')),
                ('link', models.CharField(max_length=64, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('id',), 'verbose_name': 'Расценка', 'verbose_name_plural': 'Расценки'},
        ),
    ]
