# Generated by Django 2.2.3 on 2019-07-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190630_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('id',), 'verbose_name': 'Расценку', 'verbose_name_plural': 'Расценки'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('id',), 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
